.\" Manpage for @@APP_NAME@@.
.TH man 1 "28 Apr 2020" "1.0" "@@APP_NAME@@ man page"
.SH NAME
@@APP_NAME@@ \- example applicationworld 
.SH SYNOPSIS
@@APP_NAME@@
.SH DESCRIPTION
@@APP_NAME@@ todo ...
.SH OPTIONS
@@APP_NAME@@ todo ...
.SH BUGS
No known bugs.
.SH AUTHOR
@@APPP_AUTHOR@@ @@AUTHOR_EMAIL@@